version: '{branch}-{build}'

platform: x86
clone_depth: 1

image:
  # TODO: check and fix
  # - Visual Studio 2019
  - Ubuntu2004

environment:
  global:
    CMAKE_BUILD_PARALLEL_LEVEL: 2
  matrix:
    - BUILD_TYPE: Release
    # - BUILD_TYPE: Debug

install:
  # Linux: install multilib compilers
  - sh: |
      sudo apt-get -qq update
      sudo apt-get -qq -y install \
          cmake gcc-11 g++-11 \
          gcc-11-multilib g++-11-multilib \
          lib32gcc-11-dev lib32stdc++6
      echo "g++ version: $(g++ --version | head -n1)"
  # initialize all submodules
  - git submodule update --init --recursive
  # apply patches
  - sh: (cd lib/cpp_redis && git apply ../../patches/fix-missing-thread-include.patch)
  # set CMake platform arg on MSVC
  - ps: |
      if ($isWindows) {
        $CMAKE_ARGS = "-AWin32", "-Thost=x86"
      } else {
        $CMAKE_ARGS = "-DCMAKE_CXX_FLAGS=-m32", "-DCMAKE_C_FLAGS=-m32"
      }

build_script:
  - cmd: mkdir build
  - sh: >
      cmake -Wno-dev
      -S .
      -B build
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      -DCMAKE_C_FLAGS=-m32
      -DCMAKE_CXX_FLAGS=-m32
  - sh: cmake --build build --config ${BUILD_TYPE}

artifacts:
  - path: 'build/plugins/*'
  - path: 'build/plugins/**/*'
